### ISSUE TITLE
Undoing a delete on a hold after selection creates a duplicated hold note

### ISSUE THREAD

**Issue by ayhyap** [Yasu3D/MercuryMapper#14] opened 2024-04-27 20:32 UTC
Selecting and deleting a hold, then undoing the delete, creates a duplicated hold note where the highlighted hold note is (with identical note entry in the .map file).

To reproduce:
- highlight a hold start/segment/end
- select it (shift+space)
- select (all?) hold note references (shift+r) ((also works if you manually select))
- delete hold (del)
- undo (ctrl+z)
There should now be a duplicated hold note at the location of the highlighted hold note.

Does not duplicate other note types, only hold start/segment/ends.
The highlighted note can be moved after selecting hold references, and the note will be duplicated wherever is highlighted.

((testing beyond this point was looking to be a headache, so I eventually stopped))
The duplicating bug can also work on other holds after selecting references, as long as at least one of the notes of the new hold are selected(?)

---
Edit:
After some thinking, I suspect this is due to the undo process not de-duplicating the re-insertion of overlapping highlighted and selected notes.

**Comment by Yasu3D** [comment] 2024-04-29 00:33
The issue was order of operations.
When deleting notes, the editor does the following:
1) for each *selected* note, add a delete operation
2) if no notes are selected, add a delete operation for the highlighted note.

Swapping these around fixed it, because `1)` essentially clears the selection =>  `selection count = 0` => it adds an extra operation for the highlight.

Thanks for the detailed steps to reproduce :)
This issue will be fixed in 1.3.0, so I'll close it.

**Closed as completed by Yasu3D** 2024-04-29 00:33 UTC
