### ISSUE TITLE
Moving cursor during previewing will cause a huge FPS drop.

### ISSUE THREAD

**Issue by traoearth** [Yasu3D/MercuryMapper#16] opened 2024-05-30 15:50 UTC

**Comment by traoearth** [comment] 2024-05-30 15:51
And stop moving it would be better.

**Comment by Yasu3D** [comment] 2024-06-05 14:36
I can reproduce this only when debugging in my IDE. Release builds work fine.
Commenting out every function related to mouse movement does not fix this.
Removing ToolTips does not fix it either.

I either missed something obvious, or this is a random Avalonia quirk that just randomly got introduced :(
If anyone else wants to try and help with this issue, that would be nice.

**Comment by Yasu3D** [comment] 2024-06-05 15:22
Ok nevermind. This is 100% caused by tooltips.

**Comment by traoearth** [comment] 2024-06-06 07:57
In 2.0.1b, It gets worse.

https://github.com/Yasu3D/MercuryMapper/assets/82272385/a63a81e7-2f91-4aa0-a707-156d5e7293fd

**Comment by Yasu3D** [comment] 2024-06-16 19:07
Fixed in latest release.

**Closed as completed by Yasu3D** 2024-06-16 19:07 UTC
Labels: help wanted
