### ISSUE TITLE
Edit Hold button does not update selected note type in the Note Type menu UI element

### ISSUE THREAD

**Issue by ayhyap** [Yasu3D/MercuryMapper#19] opened 2024-06-13 14:01 UTC
(Version 2.0.1b)

Edit Hold changes the selected note type to Hold.
Upon ending Hold, the selected note type will remain as Hold, but the selected note type in the note type menu will be whatever was selected prior to editing the hold.

To reproduce:
1. Place a hold
2. Select Touch note type
3. Highlight the hold end segment
4. Edit hold
5. (optionally add a new hold segment)
6. End hold

The note indicator/preview thing is now a hold, but the note type menu indicates touch.
Placing a note will place a hold as normal.
Switching to touch requires selecting a different note type, then selecting touch again.

--

Separately, edit hold mode will not toggle when using undo - one needs to manually end hold.

**Comment by Yasu3D** [comment] 2024-06-13 14:39
Undo not ending a hold is intended behavior. Other issues will be fixed in next release.

**Comment by ayhyap** [comment] 2024-06-13 14:44
To clarify, undo does not end [edit hold] even after one has gone past hold actions, and will need to be manually ended to continue adding notes.

**Comment by Yasu3D** [comment] 2024-06-13 16:20
correct. that is intended behavior.

**Comment by Yasu3D** [comment] 2024-06-16 19:06
Fixed in latest release.

**Closed as completed by Yasu3D** 2024-06-16 19:06 UTC
